### PR TITLE
Remove maven-assembly-plugin to unbundle dependencies

### PR DESCRIPTION
**Pull request by msgilligan**
Should resolve Issue #70.

### CODE REVIEW

**Comment by johncarl81** [comment]
Like [I mentioned](https://github.com/asciidoctor/asciidoclet/issues/70#issuecomment-401619486), I think we should support both a regular and uber jar.

**Comment by johncarl81** [comment]
@reckart I don't think so because this is used as a library, not an executable.
@msgilligan what do you think of my proposed shade plugin snippet?

**Comment by msgilligan** [comment]
In general, I've found that life is simplest when a build module/submodule produces a single artifact. Whenever I make shade jars I often regret the extra complexity. You end up with two Jars that must be published/distributed/distinguished.

If the shade plugin works and you really want to continue to support this use case, let's close this PR and make a new one.

**Comment by johncarl81** [comment]
Let me know what you think @msgilligan: https://github.com/asciidoctor/asciidoclet/pull/86

**Comment by msgilligan** [comment]
Closing in favor of #86 .

**Pull request closed without merging**
