### PR TITLE
Add links to README and Powered-by document.

### PR DESCRIPTION
**Pull request by msgilligan**
Addresses:

* Issue #46 (partially - adds link to JavaDoc JAR, we still should publish exploded JavaDoc)
* Issue #47 (partially)
* Issue #48 (can be closed now)

### CODE REVIEW

**Comment by mojavelinux** [comment]
To follow conventions elsewhere in the project, I think the docs should be in the following folder:

```
src/docs/asciidoc
```

(or just `src/docs`).

I'd also be okay with `docs`, but it's my third choice.

**Comment by msgilligan** [comment]
I see your point. Personally, I hate that convention. I like the documentation to be easy to find (even for people who aren't from a development or Java background and aren't used to such deep folder nesting) I also don't see why documentation should be party of the "source code".

But it's not my project, and I do understand the value of conventions. -- I prefer `src/docs` to `src/docs/asciidoc`, though -- as little nesting as possible for the docs :)

Tell me where you want it and I'll update the pull request.

**Comment by mojavelinux** [comment]
@johncarl81 What's your preference?

It needs to at least be "docs" I think (as otherwise it seems like it only contains a single document).

**Comment by johncarl81** [comment]
I like `src/docs/asciidoc`.. follows the maven structure of `src/main/java` (for instance).

I think we can keep the page discoverable by linking to it from the README.  WDYT?

**Comment by mojavelinux** [comment]
:+1: Good thinking.

**Comment by msgilligan** [comment]
OK 87011195524124a7fec035ee43bde3e812d332c7 moves the document to `src/docs/asciidoc` 

Note: You'll see I'm using an absolute link from the README. Feel free to change that after the merge. I'd like to learn what the best practice for that is when writing relative links on Github.

**Comment by mojavelinux** [comment]
> I'd like to learn what the best practice for that is when writing relative links on Github.

The best practice is a bit of a hack right now, but here's what I do

```
= Document Title
ifdef::env-github[:outfilesuffix: .adoc]

<<path/to/document.adoc#,label>>
```

**Comment by msgilligan** [comment]
Thanks @mojavelinux - relative links are implemented. Pull request should be completely ready to go now.

**Comment by mojavelinux** [comment]
:+1: Nice job!

**Comment by msgilligan** [comment]
@johncarl81 Is this one ready to merge? Is there anything else I need to do before it can be accepted?

**Comment by mojavelinux** [comment]
Looks good to me.

**Comment by johncarl81** [comment]
Oops, sorry for the delay...

**Pull request merged**
