### PR TITLE
Upgraded to latest asciidoctorj

### PR DESCRIPTION
**Pull request by johncarl81**

### CODE REVIEW

**Comment by msgilligan** [comment]
Is there an issue preventing this PR from being merged? Can/should we upgrade to asciidoctorj 1.5.6?

**Comment by johncarl81** [comment]
Only that I don't like to merge my own PRs :wink:.  I upgraded to 1.5.6 too.

**Comment by msgilligan** [comment]
I can help with that if you like :-)

**Comment by msgilligan** [comment]
So, can we get @mojavelinux to merge this one?

**Comment by johncarl81** [comment]
If you want to merge it, go ahead @msgilligan

**Comment by msgilligan** [comment]
I don't have write access to this repo, but I'm hinting...

**Comment by msgilligan** [comment]
I would happily accept. 👍

**Comment by mojavelinux** [comment]
Awesome! I'll add you then. Welcome aboard!

**Comment by mojavelinux** [comment]
Visit https://github.com/asciidoctor to accept.

**Pull request merged**
