### PR TITLE
Migrate docs to Antora site

### PR DESCRIPTION
**Pull request by abelsromero**
Migrates the README and _src/docs/asciidoc/asciidoclet-powered.adoc_ to an Antora structure under _docs_ directory.

NOTE: Kept the doc `release-process.adoc` out of the site because is not complete and I am not sure it fits.

I kept the same structure except for:
* Renamed `Introduction` section to `Getting Started`. This page contains the examples so to me it makes sense.
* Converted `Log Warning` below `Usage` section into a Warning admonition inside `Usage`

### CODE REVIEW

**Comment by abelsromero** [comment]
I tested the generated `target/apidocs/overview-summary.html` file with the new overview.adoc and I could generate the same as now using an include with as exclusion :v:

**Comment by abelsromero** [comment]
Ready for review. This is the toc
image

**Comment by abelsromero** [comment]
Fixed the references to options in _Usage.adoc_ so they work both in the HTML for the doctlet and Antora.

With that, no more changes from my site :+1:

**Comment by mojavelinux** [comment]
The docs.asciidoctor.org site is about to go live and I'd love to see the Asciidoclet documentation there when we launch. We even have a space reserved for it in the navbar. @johncarl81 or @msgilligan, could you have a look and approve if you're on board?

**Comment by johncarl81** [comment]
Looks good to me!

**Review by johncarl81 — APPROVED** [review]

**Pull request merged**
