### PR TITLE
Update to AsciidoctorJ 1.5.7

### PR DESCRIPTION
**Pull request by msgilligan**
* Upgrade to AsciidoctorJ 1.5.7
* Bump OUR version to 1.5.7-SNAPSHOT to reflect that
* Update to latest slf4j-simple — 1.7.25 
* Update to latest Guava for Java 1.6 - 20.0

### CODE REVIEW

**Comment by msgilligan** [comment]
I think there are still some issues with AsciidoctorJ 1.5.7 -- see the latest discussion on Issue #45 ...

**Comment by mojavelinux** [comment]
I'm wondering if the problem we're having with AsciidoctorJ 1.5.7 / JRuby 9 is being caused by Guava or some other dependency. I cannot reproduce the problem anywhere else except Asciidoclet.

If worse comes to worse, we'll just have to roll out another release that includes the following change to Asciidoctor core. See https://github.com/asciidoctor/asciidoctor/commit/20c8c9bdc75dc8cb4a3e168c9c61751ed5182139

Aside from that problem, everything else seems to work great.

**Comment by johncarl81** [comment]
Taking a look :eyes:

**Comment by msgilligan** [comment]
@mojavelinux @johncarl81 What are the next steps?

**Comment by johncarl81** [comment]
I'll defer to @mojavelinux for the Asciidoctor issue here.  For Asciidoclet, we could convert the haml over to the other template language (forgot the name and can't find the reference atm).

**Comment by johncarl81** [comment]
Looks like the error is present even if we don't specify the haml templates.

**Comment by johncarl81** [comment]
@msgilligan I think we need to wait on upgrading to 1.5.7 until https://github.com/asciidoctor/asciidoclet/issues/45 is resolved.  In the mean time we can issue a release of 1.5.6.  WDYT?

**Comment by msgilligan** [comment]
Sounds like a plan. Closing...

**Comment by msgilligan** [comment]
I'd like to submit a PR bumping Guava and slf4j and also making the version 1.5.6-SNAPSHOT, sound good?

**Comment by johncarl81** [comment]
Sounds great @msgilligan !

**Pull request closed without merging**
